
### GET /health_check

GET http://localhost:8000/health_check


### POST /subscriptions

POST http://localhost:8000/subscriptions
Content-Type: application/x-www-form-urlencoded

name=John212+Doe&email=john212222.doe@example.com


### digital ocean

GET https://zero2prod-och9u.ondigitalocean.app/health_check



### post

POST https://zero2prod-och9u.ondigitalocean.app/subscriptions
Content-Type: application/x-www-form-urlencoded

name=le%20guin&email=john2222.doe@example.com