application:
  port: 8000
  # You need to set the `APP_APPLICATION__HMAC_SECRET` environment variable 
  # on Digital Ocean as well for production!
  hmac_secret: "my-secret-tokenadfsdfsfdskfljdsklfmy-secret-tokenadfsdfsfdskfljdsklf"

database:
  username: "postgres"
  password: "password"
  host: "localhost"
  port: 5431
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "newsletter@example.com"
  authorization_token: "my-secret-tokenadfsdfsfdskfljdsklfmy-secret-tokenadfsdfsfdskfljdsklf"
  timeout_milliseconds: 10000
